### ISSUE TITLE
Clearfix on div wrapper

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#59]
Add:

```CSS
body > div:after{
content:"";
display:table;
clear:both;
}
```
